import packageFile from "../package.json" with { type: "json" };

export default {
  owner: "Yellow Hoshino",
  ownerNum: ["6285198221676", "6281328082627"], //
  botName: "Yuzi Bot",
  prefix: ".",
  botVersion: packageFile.version,

  sessionName: "yuzi_session",
  baileys: "@whiskeysockets/baileys",
  // thumb: "https://i.ibb.co.com/ksts181G/thumb.jpg",
  thumb:
    "https://i.ibb.co.com/DDQ1vq2v/014a1dd5-a38e-426d-bb8e-6ce949d57bc3.jpg",
  // thumb: "https://i.ibb.co.com/yF800TMc/IMG-20260524-WA0017.jpg",
  // Persona AI
  aiGender: "female",
  aiAge: "18",
  aiPersonality: ["cheerfully", "teasing", "cute", "kind", "mysterious"],
  aiChatGenre: ["romance", "slice of life"],
  /**
   * Custom pairing code (8 alphanumeric chars after removing hyphens).
   * Examples:
   *   "ADBC-DAKS" → becomes "ADBCDAKS"
   *   "1234-4321" → becomes "12344321"
   *   "STARFALL"  → 8-letter code
   * Set to null for random code generated by WhatsApp
   */
  pairingCode: "STARFALL",
};

// List baileys
// baileys: "@whiskeysockets/baileys"
// baileys: "@itsliaaa/baileys"
// baileys: "baileys"
