import axios from "axios";
import chalk from "chalk";
import { createCanvas, loadImage } from "canvas";

export default {
  package: "PageSpeed Audit",
  command: ["pagespeed", "psi"],
  owner_only: true,
  description: "Cek performa website menggunakan Google PageSpeed",
  category: "tools",

  async run(yuzi, msg, { args }) {
    if (!args[0]) {
      return await yuzi.sendMessage(
        msg.key.remoteJid,
        {
          text: "Masukkan URL website.\n\nContoh:\n.pagespeed https://example.com",
        },
        { quoted: msg },
      );
    }

    const target = args[0];

    try {
      const { data } = await axios.get(
        `https://api.silentkana.web.id/api/tools/pagespeed?url=${encodeURIComponent(target)}`,
      );

      if (!data?.result?.length) {
        return await yuzi.sendMessage(
          msg.key.remoteJid,
          {
            text: "Gagal mengambil data PageSpeed.",
          },
          { quoted: msg },
        );
      }

      const canvas = createCanvas(1600, 900);
      const ctx = canvas.getContext("2d");

      const gradient = ctx.createLinearGradient(0, 0, 1600, 900);
      gradient.addColorStop(0, "#0f172a");
      gradient.addColorStop(1, "#020617");

      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      ctx.fillStyle = "#ffffff";
      ctx.font = "bold 58px Sans";
      ctx.fillText("PageSpeed Insight", 70, 100);

      ctx.fillStyle = "#94a3b8";
      ctx.font = "28px Sans";
      ctx.fillText(`Target: ${target}`, 70, 145);

      const cards = [
        {
          x: 70,
          y: 220,
          data: data.result.find((x) => x.device === "mobile"),
          color: "#22c55e",
        },
        {
          x: 830,
          y: 220,
          data: data.result.find((x) => x.device === "desktop"),
          color: "#3b82f6",
        },
      ];

      function drawRoundedRect(x, y, w, h, r) {
        ctx.beginPath();
        ctx.moveTo(x + r, y);
        ctx.lineTo(x + w - r, y);
        ctx.quadraticCurveTo(x + w, y, x + w, y + r);
        ctx.lineTo(x + w, y + h - r);
        ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
        ctx.lineTo(x + r, y + h);
        ctx.quadraticCurveTo(x, y + h, x, y + h - r);
        ctx.lineTo(x, y + r);
        ctx.quadraticCurveTo(x, y, x + r, y);
        ctx.closePath();
      }

      function drawProgressBar(x, y, width, value, color) {
        ctx.fillStyle = "#1e293b";
        drawRoundedRect(x, y, width, 22, 12);
        ctx.fill();

        ctx.fillStyle = color;
        drawRoundedRect(x, y, (width * value) / 100, 22, 12);
        ctx.fill();
      }

      for (const card of cards) {
        const scores = card.data.scores;

        drawRoundedRect(card.x, card.y, 700, 560, 35);
        ctx.fillStyle = "#111827";
        ctx.fill();

        ctx.fillStyle = "#ffffff";
        ctx.font = "bold 44px Sans";
        ctx.fillText(card.data.device.toUpperCase(), card.x + 40, card.y + 70);

        const average = Math.round(
          Object.values(scores).reduce((a, b) => a + b, 0) /
            Object.values(scores).length,
        );

        ctx.beginPath();
        ctx.arc(card.x + 580, card.y + 90, 70, 0, Math.PI * 2);
        ctx.fillStyle = "#1e293b";
        ctx.fill();

        ctx.beginPath();
        ctx.arc(
          card.x + 580,
          card.y + 90,
          70,
          -Math.PI / 2,
          (Math.PI * 2 * average) / 100 - Math.PI / 2,
        );
        ctx.lineWidth = 14;
        ctx.strokeStyle = card.color;
        ctx.stroke();

        ctx.fillStyle = "#ffffff";
        ctx.font = "bold 34px Sans";
        ctx.textAlign = "center";
        ctx.fillText(average.toString(), card.x + 580, card.y + 102);

        ctx.textAlign = "left";

        const entries = [
          ["Performance", scores.performance],
          ["Accessibility", scores.accessibility],
          ["Best Practices", scores.bestPractices],
          ["SEO", scores.seo],
        ];

        let posY = card.y + 190;

        for (const [label, value] of entries) {
          ctx.fillStyle = "#e5e7eb";
          ctx.font = "30px Sans";
          ctx.fillText(label, card.x + 40, posY);

          ctx.fillStyle = "#94a3b8";
          ctx.font = "bold 28px Sans";
          ctx.fillText(`${value}`, card.x + 600, posY);

          drawProgressBar(
            card.x + 40,
            posY + 25,
            600,
            value,
            value >= 90 ? "#22c55e" : value >= 70 ? "#eab308" : "#ef4444",
          );

          posY += 95;
        }
      }

      ctx.fillStyle = "#475569";
      ctx.font = "24px Sans";
      ctx.fillText(`Generated by ${data.creator}`, 70, 860);

      const buffer = await canvas.encode("png");

      await yuzi.sendMessage(
        msg.key.remoteJid,
        {
          image: buffer,
          caption: `PageSpeed result untuk ${target}`,
        },
        { quoted: msg },
      );
    } catch (err) {
      console.error(chalk.red("[-] [PAGESPEED]"), err);

      await yuzi.sendMessage(
        msg.key.remoteJid,
        {
          text: "Terjadi kesalahan saat mengambil data PageSpeed.",
        },
        { quoted: msg },
      );
    }
  },
};
